### ISSUE TITLE
Runtime Exception when build from Source 

### ISSUE THREAD

**Issue by pcgayan** [chilicat/JsChilicat#11]
seems like when download the source compile and run you get an null point exception.

When I debug, I got to know lib/jschilicat.js is loaded from current location and not from root of classloader.

JsMessageBusInit ->createInScope: 
InputStream in = MessageBusFactory.class.getResourceAsStream("lib/jschilicat.js");

This needs to be changed as:
InputStream in = MessageBusFactory.class.getResourceAsStream("/lib/jschilicat.js");

Notiec the "/" beginning of lib/jschilicat.js.

**Comment by chilicat** [comment]
It seems like to be correct, please see:
https://github.com/chilicat/JsChilicat/blob/master/JsChilicat/src/main/java/net/chilicat/testenv/js/JsMessageBusInit.java#L100

**Comment by pcgayan** [comment]
Thanks a lot, may be I have been mistaken.
