### ISSUE TITLE
Tests from second js file fail with 'WAITING'

### ISSUE THREAD

**Issue by ebatzdor** [chilicat/JsChilicat#14]
All tests from first file picked up run as expected.  All tests from subsequent file fail with a 'WAITING' message.  

I must be doing something wrong, but I've set up the simplest possible scenario and the issue is still happening.  

Any pointers how to resolve this?    Here's a link to all the code...
https://docs.google.com/open?id=0B7kT5Ybf-3ALd0pLZEp0bWRmU3c

And enclosed is the console output when I attempt to run the tests.

Any help is appreciated.

Thanks,

Eric

c:\temp\jschilitcatissue>java -jar lib/jschilicat.jar -src js -src-test test/js -workingDir out 
Dec 6, 2012 10:35:30 AM net.chilicat.cmd.CommandArguments logOptions
INFO: Options:
 -src-test test/js
 -workingDir out
 -src js
Dec 6, 2012 10:35:30 AM org.restlet.engine.http.StreamServerHelper start
INFO: Starting the internal HTTP server
Dec 6, 2012 10:35:30 AM net.chilicat.testenv.Application printSetup
##  Lib Files

---

---
##  Source Files

```
    js
```

---

---
##  Test Files

```
    test\js\helloQunitTest1.js
    test\js\helloQunitTest2.js
```

---

Dec 6, 2012 10:35:30 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: jschilicat.js Time: 46 ms
Dec 6, 2012 10:35:31 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: <jar-resource>/lib/env.js Time: 1421 ms
Dec 6, 2012 10:35:32 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: <jar-resource>/lib/env-driver.js Time: 1 ms
Dec 6, 2012 10:35:32 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: <jar-resource>/lib/qunit.js Time: 15 ms
Dec 6, 2012 10:35:32 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: <jar-resource>/lib/qunit_adapter.js Time: 1 ms
Dec 6, 2012 10:35:32 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: c:\temp\jschilitcatissue\test\js\helloQunitTest1.js Time:
0 ms
Dec 6, 2012 10:35:32 AM net.chilicat.testenv.model.DefaultTestReportModel$Bus te
stScriptDone
INFO:
# 

Module: 'C:\temp\jschilitcatissue\test\js\helloQunitTest1.js' Test Cases: '2'

```
    Test Case Name: 'hello test1' Passed
    Test Case Name: 'hello test2' Passed
```
# 

Dec 6, 2012 10:35:32 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2012-12-06        10:35:32        127.0.0.1       -       -       8182
GET     /rhino_index.html       -       200     -       -       2       http://l
ocalhost:8182   Java/1.6.0_27   -
Dec 6, 2012 10:35:33 AM net.chilicat.testenv.rhino.RhinoTestExecutor compileScri
pt
INFO: Compile Script: c:\temp\jschilitcatissue\test\js\helloQunitTest2.js Time:
0 ms
Dec 6, 2012 10:35:33 AM net.chilicat.testenv.model.DefaultTestReportModel$Bus te
stScriptDone
INFO:
# 

Module: 'C:\temp\jschilitcatissue\test\js\helloQunitTest2.js' Test Cases: '2'

```
    Test Case Name: 'hello test3' Passed
    Test Case Name: 'hello test4' Passed
```
# 

Dec 6, 2012 10:35:33 AM org.restlet.engine.log.LogFilter afterHandle
INFO: 2012-12-06        10:35:33        127.0.0.1       -       -       8182
GET     /rhino_index.html       -       200     -       -       1       http://l
ocalhost:8182   Java/1.6.0_27   -
Dec 6, 2012 10:35:33 AM net.chilicat.testenv.report.FailedTestsReport generate
WARNING:
Module: helloQunitTest1.js -- C:\temp\jschilitcatissue\test\js\helloQunitTest1.j
s
failed

Module: helloQunitTest2.js -- C:\temp\jschilitcatissue\test\js\helloQunitTest2.j
s
        Test: hello test3 failed (WAITING)
        Test: hello test4 failed (WAITING)
failed

Result: 2 of 4 Test(s) failed

**Comment by chilicat** [comment]
For me everything looks ok, except that in my example tests I also specify a module:

``` javascript
   module("Class basics");

   test("Interface", function() {
    ok(Class);
    ok(Class.extend);
   });
```

please try to specify for each file a module.

**Comment by ebatzdor** [comment]
Thanks!  That fixed the issue.

And another thanks for the quick response.

-Eric
