### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by valerie7869** [chilicat/JsChilicat#15]
Is this project have an open source license? thanks

**Comment by chilicat** [comment]
Hi Valerie,
Do what ever good stuff you want to do with it. Please OpenSource your
ideas or modifications if possible.

**Comment by valerie7869** [comment]
Hi Daniel
Thanks very much for your reply- however, I am still uncertain of the license status of your code...

I am researching the license obligations for a commercial company using this code.  Ambiguous licensing can be a problem for many.
Can I conclude there is no officially declared license for this?

Thanks again for clarification-
Valerie Douglas

**Comment by chilicat** [comment]
Hi Valerie,

I have added a license to the readme:
https://github.com/chilicat/JsChilicat/blob/master/README.creole
