### ISSUE TITLE
Plugin does not pick order of JS files for loading. It always pick based on alphabetical order of file name.

### ISSUE THREAD

**Issue by praves77** [chilicat/JsChilicat#2]
For my app to work properly, I need to specify order in which JS files should be loaded. I am using Modenizr(v2, which has inbuilt yepnope.js). How do I specify JS files (& their order) that should be loaded for unit test to work? 

Thanks.

**Comment by chilicat** [comment]
Hi Praves,

jschilicat allows you to specifiy libraries, sources and test files. The difference between those three is that libraries and test files will not be considered in the reports (for example coverage). 

The modenizer is in my eye a library. You are able to specify a list of lib files like: 

java -jar jschilicat.jar -libs=libs/mylib1.js;libs/mylib2.js -src=... -src-test=...

best regards,
Daniel

**Comment by chilicat** [comment]
Please let me know if that will fix your issue.

**Comment by praves77** [comment]
Thank you, Daniel for clarification about usage of library (in this case 
Modernizr). I appreciate your help. I am new to JS programming, so please bear 
with me.

I still could not resolve my issue. I've about 219 different JS files spread 
across different sub-folders of source directory. As you know, for app to work 
these JS files should be loaded in predefined sequential order (otherwise some 
objects will be undefined), that's what happening with me.

I tried following:
1) By copying all of source files in 'src', folder test files in 'src-test' and 
libraries in 'libs' folder of root directory. I'm getting error 'undefined' 
object while one source file is being loaded. I've attached log file for more 
info.
2) Copied all source and libraries in one folder and still got the same error.
3) I've attached log file 'jsChilicatError.log'

Few more info:
1) Our tests use DOM objects also which cause some of tests to fail in 
non-browser mode.
2) I could not make your test sample (included in download) work for any browser 
Chrome v12 or FireFox v3.6. It throws timeout exception (while looking for 
favicon.ico).
3) I have attached log file 'jsChilicatChromeError.txt' for this too. 

Regards,

---

From: chilicat 
reply@reply.github.com
To: tester9977@yahoo.com
Sent: Fri, July 1, 2011 1:43:01 AM
Subject: Re: [JsChilicat] Plugin does not pick order of JS files for loading. It 
always pick based on alphabetical order of file name. (#2)

Hi Praves,

jschilicat allows you to specifiy libraries, sources and test files. The 
difference between those three is that libraries and test files will not be 
considered in the reports (for example coverage). 

The modenizer is in my eye a library. You are able to specify a list of lib 
files like: 

java -jar jschilicat.jar -libs=libs/mylib1.js;libs/mylib2.js -src=... 
-src-test=...

best regards,
Daniel

## 

Reply to this email directly or view it on GitHub:
https://github.com/chilicat/JsChilicat/issues/2#issuecomment-1481508
5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30    http://localhost:8182/datamappingsTest.js.html
     [java] Jul 3, 2011 8:20:27 PM org.restlet.engine.log.LogFilter afterHandle
     [java] INFO: 2011-07-03    20:20:27        127.0.0.1       -       -       8182    GET     /test-files/qunit       -       200     -       -       20      http://localhost:8182   Mozilla/5.0 (Win
dows NT 6.1; WOW64) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30    http://localhost:8182/datamappingsTest.js.html
     [java] Jul 3, 2011 8:20:27 PM org.restlet.engine.log.LogFilter afterHandle
     [java] INFO: 2011-07-03    20:20:27        127.0.0.1       -       -       8182    GET     /test-files/yepnope.js  -       200     19619   -       0       http://localhost:8182   Mozilla/5.0 (Win
dows NT 6.1; WOW64) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30    http://localhost:8182/datamappingsTest.js.html
     [java] Jul 3, 2011 8:20:27 PM org.restlet.engine.log.LogFilter afterHandle
     [java] INFO: 2011-07-03    20:20:27        127.0.0.1       -       -       8182    GET     /test-files/datamappingsTest.js -       200     275     -       0       http://localhost:8182   Mozilla/
5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30    http://localhost:8182/datamappingsTest.js.html
     [java] Jul 3, 2011 8:20:27 PM org.restlet.engine.log.LogFilter afterHandle
     [java] INFO: 2011-07-03    20:20:27        127.0.0.1       -       -       8182    GET     /favicon.ico    -       404     363     -       1       http://localhost:8182   Mozilla/5.0 (Windows NT
6.1; WOW64) AppleWebKit/534.30 (KHTML, like Gecko) Chrome/12.0.742.100 Safari/534.30    -
     [java] net.chilicat.testenv.core.TestEnvException: Timeout exception
     [java]     at net.chilicat.testenv.webdriver.AbstractWebDriverTestExecutor$Bus.await(Unknown Source)
     [java]     at net.chilicat.testenv.webdriver.AbstractWebDriverTestExecutor.execute(Unknown Source)
     [java]     at net.chilicat.testenv.Application.execute(Unknown Source)
     [java]     at net.chilicat.testenv.Main.main(Unknown Source)
     [java] Jul 3, 2011 8:20:57 PM net.chilicat.testenv.Application execute
     [java] SEVERE: Timeout exception
     [java] Java Result: -1

**Comment by chilicat** [comment]
> > I still could not resolve my issue. I've about 219 different JS files spread
> > across different sub-folders of source directory. As you know, for app to work
> > these JS files should be loaded in predefined sequential order (otherwise some
> > objects will be undefined), that's what happening with me.

Here is the same thing like with the library. chilicat is not able to figure out the order automagical. You must specify the order in command line (do you use the command line?). Instead of folders you must specify the fiels. Is a lot of work for 219 files :)

java -jar jschilicat.jar -libs=libs/mylib1.js;libs/mylib2.js -src=src/B.js;src/A.js;src/C.js -src-test=test/BTest.js;test/ATest.js;test/CTest.js

Regarding the DOM tests. jschilicat has a DOM simulation. It is called envjs. Depending on the code it could work.

**Comment by praves77** [comment]
Thank you.

Is it too much of work if these file names are provided in an input file (say source.jsl, test.jsl and libs.jsl)? for example:
java -jar jschilicat.jar -libs=libs/mylibList.jsl -src=src/sources.jsl -src-test=test/myTests.jsl 

where: 
  mylibList.jsl --> contains list of libraries as we provide in command line
       libs/mylib1.js;
       libs/another/mylib2.js;
       libs/mylib3.js;
       libs/mylib4.js

  sources.jsl --> contains list of sources in sequential order as we provide in command line
       src/srcA.js;
       src/data/srcB.js;
       src/disp/srcC.js;
       src/srcD.js

  myTests.jsl --> contains list of test files as we provide in command line
       src-test/testA.js;
       src-test/testB.js;
       src-test/testC.js;
       src-test/testD.js

I can build the new library if you can point me where to make these changes (which file).

Once again thank you for your help.

One more thing I could not test your samples in browser. It failed with timeout error. Any idea?

**Comment by chilicat** [comment]
The .jsl file suport should be easy.

The structure wouls look like:

project 
------+ myTest.jsl 
------+ src-test
----------------+ testA.js
----------------+ testB.js

I tried it on my machine and it works for firefox 3.6 but not for the google chrome.
I have upgraded to newest version of firefox. It didn't work at all.

I was able to fix the firefox problem by upgrading the selenium driver. 

You can find the newsest driver here:
http://code.google.com/p/selenium/downloads/detail?name=selenium-server-standalone-2.0rc3.jar&can=2&q=

rename the downloaded jar file to selenium-server-standalone-2.0a5.jar and copy it into the "jschilicat/libs" directory

I will integrate the newest driver soon.

**Comment by chilicat** [comment]
javascript list files (.jsl) are now supported. I have comitted the chnages to the repository.

You must not use a semicolon in case of each file is in a new line.
Both are allowed:

B.js
C.js
A.js

Or 

B.js;C.js;A.js

**Comment by praves77** [comment]
Thank you, Daniel!

I tried to download zipped package 'jschilicat.zip' and got Access denied message as follows. jschilicatIdea.zip was accessible:

"<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>7D5196E0DFA7DBE1</RequestId>
<HostId>
qCP86Erp2uLdQtx2QiSk6IV1y0u/MvpJHF6SNGXPaWlue9njTdJHx9YEK3g+011K
</HostId>
</Error>"

Two more questions: 
1) Is there way to supply timeout in parameter? I was getting timeout error also and my tests generally takes more than 12000 milliseconds to complete. I will let you know once I get new plugin installed.
2) I have proxy settings. Is there way I can supply proxy settings or profile template for Firefox or Chrome driver for Selenium? May be this is the reason for timeout? Firefox always uses System-Proxy settings (which never works if there is proxy settings) when Firefox is launched via command line.

**Comment by chilicat** [comment]
I have uploaded a new distribution.

1) The timeout is currently 30 seconds per test file. The timeout is a system settings. You could set it with the 
-DtestTimeout=30000

the time is in milliseconds.

2) Currently not it is not possible. I'm not sure about the proxy because I didn't use it myself so far.

**Comment by praves77** [comment]
Thank you, Daniel for reply.
Please bear with me, I don't know where is -DtestTimeout" defined. FYI, I am 
using Windows 7. 

Now tests bundled with current distribution work fine in all environment 
(default & Firefox) after I upgraded to Firefox 5.0.

My unit testing is still failing because of Modernizr library 
(modernizr-latest.js is downloadable 
from http://www.modernizr.com/downloads/modernizr-latest.js). 

I tried testing your test samples by including modernizr (to reproduce the 
problem) library as follows:
-libs=./intellij-test-project/src/main/lib/jquery.js;./intellij-test-project/src/main/lib/modernizr-latest.js

I got the same error 'offsetTop' undefined in Modernizr.js#267 (please see 
attached file's line# 58). Do you think something can be done to fix this error? 
Please let me know.

Thanks a lot for your help. I appreciate it.

Attachment did not show up here, so pasting some of logs info:

```
 [java] ------------------
 [java]  Test Files 
 [java] ------------------
 [java]     C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\test\js\org\ejohn\AClassTest.js
 [java]     C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\test\js\org\ejohn\BClassTest.js
 [java]     C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\test\js\org\ejohn\CClassTest.js
 [java]     C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\test\js\org\ejohn\ClassTest.js
 [java]     C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\test\js\org\ejohn\DClassTest.js
 [java]     C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\test\js\org\other\COMTest.js
 [java]  
 [java] ------------------
 [java] Jul 7, 2011 4:15:20 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: jschilicat.js Time: 19 ms
 [java] Jul 7, 2011 4:15:20 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: <jar-resource>/lib/env.js Time: 265 ms
 [java] Jul 7, 2011 4:15:20 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: <jar-resource>/lib/env-driver.js Time: 1 ms
 [java] Jul 7, 2011 4:15:20 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: <jar-resource>/lib/qunit.js Time: 4 ms
 [java] Jul 7, 2011 4:15:20 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: <jar-resource>/lib/qunit_adapter.js Time: 0 ms
 [java] Jul 7, 2011 4:15:20 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\jquery.js Time: 28 ms
 [java] Jul 7, 2011 4:15:21 PM net.chilicat.testenv.rhino.RhinoTestExecutor compileScript
 [java] INFO: Compile Script: C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js Time: 4 ms
 [java] org.mozilla.javascript.EcmaError: TypeError: Cannot read property "offsetTop" from undefined (C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js#267)
 [java]     at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3654)
 [java]     at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3632)
 [java]     at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3660)
 [java]     at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3679)
 [java]     at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3692)
 [java]     at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1421)
 [java]     at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3027)
 [java]     at script(C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js:267)
 [java]     at script(C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js:104)
 [java]     at script(C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js:255)
 [java]     at script(C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js:251)
 [java]     at script(C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js:25)
 [java]     at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2487)
 [java]     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:164)
 [java]     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
 [java]     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
 [java]     at org.mozilla.javascript.InterpretedFunction.exec(InterpretedFunction.java:175)
 [java]     at net.chilicat.testenv.rhino.RhinoTestExecutor.executeScript(Unknown Source)
 [java]     at net.chilicat.testenv.rhino.RhinoTestExecutor.loadScript(Unknown Source)
 [java]     at net.chilicat.testenv.rhino.RhinoTestExecutor.loadLibs(Unknown Source)
 [java]     at net.chilicat.testenv.rhino.RhinoTestExecutor.setup(Unknown Source)
 [java]     at net.chilicat.testenv.Application.execute(Unknown Source)
 [java]     at net.chilicat.testenv.Main.main(Unknown Source)
 [java] Jul 7, 2011 4:15:21 PM net.chilicat.testenv.Application execute
 [java] SEVERE: TypeError: Cannot read property "offsetTop" from undefined (C:\workspace\jsChilicat\jschilicat-dist\intellij-test-project\src\main\lib\modernizr-latest.js#267)
```

qunit-report:
[junitreport] Processing C:\workspace\jsChilicat\jschilicat-dist\out\junit\TESTS-TestSuites.xml to C:\AppData\Local\Temp\null1894123967
[junitreport] Loading stylesheet jar:file:/C:/apache-ant-1.8.2/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 241ms
[junitreport] Deleting: C:\AppData\Local\Temp\null1894123967

default:
     [echo] See 'C:\workspace\jsChilicat\jschilicat-dist/out/coverage' for coverage report. 
     [echo] See 'C:\workspace\jsChilicat\jschilicat-dist/out/junit' for junit report. 

BUILD SUCCESSFUL
Total time: 3 seconds

**Comment by chilicat** [comment]
The -DtestTimeout is a normal java paramter. For example: 
java -Dparam=value -jar my.jar

Currently it is not possible to set the timeout in the intellij plugin.

You have to patch the Modernizr library to get it work. I have submitted a bugfix to the Modernizr project
https://github.com/Modernizr/Modernizr/pull/319
- lets see if there accept it.

You have to replace following lines (modernizr-latest.js, line: 267):

/_>>touch_/           Modernizr['touch'] = ('ontouchstart' in window) || (hash['touch'] && hash['touch'].offsetTop) === 9; /_>>touch_/
            /_>>csstransforms3d_/ Modernizr['csstransforms3d'] = hash['csstransforms3d'].offsetLeft === 9;          /_>>csstransforms3d_/
            /_>>generatedcontent_/Modernizr['generatedcontent'] = hash['generatedcontent'].offsetHeight >= 1;       /_>>generatedcontent_/

with:

/_>>touch_/           Modernizr['touch'] = ('ontouchstart' in window) || (hash['touch'] && hash['touch'].offsetTop) === 9; /_>>touch_/
            /_>>csstransforms3d_/ Modernizr['csstransforms3d'] = (hash['csstransforms3d'] && hash['csstransforms3d'].offsetLeft) === 9;          /_>>csstransforms3d_/
            /_>>generatedcontent_/Modernizr['generatedcontent'] = (hash['generatedcontent'] && hash['generatedcontent'].offsetHeight) >= 1;       /_>>generatedcontent_/

than at least loading of the library works.

**Comment by praves77** [comment]
After updating modenizr myself, I'm able to run tests but it fails because of timeout as pasted below:

---

# 

Module: 'testDataManagers' Test Cases: '0'

Module: 'Product and Listing Manager tests' Test Cases: '5'

```
    Test Case Name: 'Create a 'fake' datasource' Passed
    Test Case Name: 'Create a 'feed' datasource' Passed
    Test Case Name: 'Create and initialize an Product Manager' Passed
    Test Case Name: 'Create and initialize a Listing Manager' Passed
    Test Case Name: 'Retrieve an item twice' Passed
```

# 

Jul 11, 2011 2:46:20 PM org.restlet.engine.log.LogFilter afterHandle
INFO: 2011-07-11        14:46:20        127.0.0.1       -       -       8182    GET     /rhino_index.html       -       200     -       -       1       http://localhost:8182   Java/1.6.0_24   -
Jul 11, 2011 2:46:20 PM org.restlet.engine.log.LogFilter afterHandle
INFO: 2011-07-11        14:46:20        127.0.0.1       -       -       8182    GET     /services/proxy.php     host=http://ussfrchihiro01.am.sony.com/docs/api/category/storeTrees/07-10-2011_16-32-00/
PN.WW.US-PN.WW.TOP.US-BASE.xml&_=1310420780669  404     363     -       1       http://localhost:8182   Java/1.6.0_24   -
Jul 11, 2011 2:46:20 PM net.chilicat.testenv.report.FailedTestsReport generate
WARNING:
Module: dataManagersTest.js -- testDataManagers
failed

Module: dataManagersTest.js -- Product and Listing Manager tests
        Test: Create a 'fake' datasource failed (WAITING)
        Test: Create a 'feed' datasource failed (WAITING)
        Test: Create and initialize an Product Manager failed (WAITING)
        Test: Create and initialize a Listing Manager failed (WAITING)
        Test: Retrieve an item twice failed (WAITING)
failed

Result: 5 of 5 Test(s) failed

---

I am not able to set timeout using java option '-DtestTimeout'.  I created an environment var then able to provide this parameter.

Is it QUnit or JUnit's system or environment variable? Once again thanks a ton.

**Comment by chilicat** [comment]
Hi Praves,

-DtestTineout is jschilicat variable. You must hand it iver over as startup paramter. 
Are you using Ant, Intellij or the commandline to execute the tests?

Can you provide me some code which reproduces the timeout problem? The stack contains no information which will help me to figureout what the problem is. Does the problem also occure in firefox or chrome? 

The only thing I don't understand is that your test seems to request " /services/proxy.php ". PHP sites are of course not supported by jshilicat. 

BTW: You can now specify firefox profiles with the commandline option: "-firefoxProfile=/path/to/firefox/directory". I haven't created a new distribution so far so you have to checkout the sources if you want to try it.

**Comment by praves77** [comment]
I was totally swamped with other work to get back to you. 

After changing some lines in unit test code, jsChilicat works perfectly fine except in case of asyncTest. Thank you.

---

We were using 'QUnit.config.reorder=false' as first thing in unit test code as QUnit will attempt to run previously failed tests first by default. This sometimes causes real problem for asynchrous test. It was not defined in your QUnit so I had to comment it out.
(Source: http://www.educatedguesswork.org/2011/06/curse_you_qunit_1.html )

## Any suggestion/thoughts on this? 

For asyncTest, I tried to set timeout (-DtestTineout in ant) as follows:
Trial 1) Passed as an argument to java.

---

   '<'target name="qunit-test"'>'
        '<'java -DtestTimeout="6000" jar="./js/jsChilicat/jsChilicat.jar" fork="true" failonerror="false"'>'  
            '<'arg value="-libs"/'>'
            '<'arg value="${testfilesDir}/testLibs.jsl"/'>'
            '<'arg value="-src"/'>'
            '<'arg value="${testfilesDir}/TestSuitesSources.jsl"/'>'
            '<'arg value="-src-test"/'>'
            '<'arg value="${testfilesDir}/testTests.jsl"/'>'
           '<'arg value="-workingDir"/'>'
            '<'arg value="${reportDir}"/'>'
            '<'arg value="-coverage"/'>'
            '<'arg value="-junitReport"/'>'
            '<'arg value="-framework"/'>'
            '<'arg value="qunit"/'>'
        '<'/java'>'
    '<'/target'>'

---

BUILD FAILED
C:\p4\chihiroMainline\build\test.jsChilicat.xml:155: Element type "java" must be followed by either attribute specifications, "'>'" or "/'>'".

Trial 2) Passed as an argument to jsChilicat.jar in ant target
   '<'target name="qunit-test"'>'
        '<'java jar="./js/jsChilicat/jsChilicat.jar" fork="true" failonerror="false"'>'
            '<'arg value="-DtestTimeout" /'>'
            '<'arg value="6000"/'>'
            '<'arg value="-libs"/'>'
            '<'arg value="${testfilesDir}/testLibs.jsl"/'>'
            '<'arg value="-src"/'>'
            '<'arg value="${testfilesDir}/TestSuitesSources.jsl"/'>'
            '<'arg value="-src-test"/'>'
            '<'arg value="${testfilesDir}/testTests.jsl"/'>'
            '<'arg value="-workingDir"/'>'
            '<'arg value="${reportDir}"/'>'
            '<'arg value="-coverage"/'>'
            '<'arg value="-junitReport"/'>'
            '<'arg value="-framework"/'>'
            '<'arg value="qunit"/'>'
        '<'/java'>'
    '<'/target'>'

jsChilicat throws SEVERE error as -DtestTimeout is not supported parameter.

---

## When I passed -DtestTimeout to command line to execute tests, it did not complain about it but I did not notice any difference in time of execution.

FYI: We're using PHP code for proxy (don't know the reason behind it). But good thing is that it was not reason for failure. *\* sigh **

I noticed that total number of tests reported by jsChilicat is equal to number of test functions in the file (not number of assertions). The QUnit's test runner (runner.html browser based test) shows total number of tests equal to total number of assertions used in the module. For example, I've total 40 assertions (in side 11 functions). QUnit's HTML based tests report 40 and jsChilliCat reports 10 (one test is not completed because of asynchronous test).

If you already know why it (async tests) might be failing please let me know. Otherwise, I will try to test aysnctest with your sample tests and see if I can make it working either by changing the test code or plugin code.

One question, which coverage tool are you using? I am not using Browser based testing as I'm also interested in coverage report. 

Once again thanks a ton! :)

**Comment by chilicat** [comment]
Hallo Praves,

good to hear that it works for you.

---

Regarding: QUnit.config.reorder=false
I do not think that qunit can remember the last failed tests in jschilicat. My assumption is that qunit will remmeber failed tests by using a cookie. In jschilicat should this cookie be lost on every execution. Did you observe any strange behavior regarding the order? Maybe I should by default set the "QUnit.config.reorder=false", just in case.

---

Regarding: Timeout
The -D parameters are java arguments. I didn't know it either that ANT will handle them differently. In ANTyou must have to do :

`<jvmarg value="-DtestTimeout" />`

The newest jschilicat version provides the timeout as real option. 

`java -jar jschilicat.jar -testTimeout 60`

or in Ant add a new params:

```
<arg value="-testTimeout"/>
<arg value="60"/>
```

---

Regarding: Assertions vs. Function
Thats because we use junit test reports as output. A junit report smallest unit is a function/method. 
In java unit tests you make usally one function per test. A test will be considered as failed if one assertion fail. That makes mostly sense because following assertion will often rely on the correct result of a previously assertion.

I can take a look if I can at least show the assertion count.

---

Regarding: Async Test cases
I never used async test cases. Maybe you can prepare me a small example test case which fails that would help me to fix the problem.

---

Regarding: Code Coverage
jschilicat supports code coverage but it has some limitations. 
1. The code coverage works only if the tests are executed in the jschilicat internal browser (rhino)
2. The code coverage is not tracking branches/conditions in one line:
            `a = b ? c : d;`
     jschilicat will just now that the line has been visit but it doesn't know that e.g. onle b==true path has been visit.

I played around with jscoverage. It seems to be promising. It also has non of the  issues I have written above but I din't see how to integrate this tool in a easy way. I also didn't like that the tool is mainly written in C which makes it harder to distribute it (at least for me because I'm a Java guy :) .

I'm actually a fan of the YUITest framework. It supports a coverage report tool like jscoverage but is  written in Java which makes it much easier to integrate the tool into jschilicat.
