### ISSUE TITLE
Is there a way to display the coverage in Jenkins?

### ISSUE THREAD

**Issue by chrkaatz** [chilicat/JsChilicat#9]
I was just thinking whether there is already a way to get the coverage data displayed in a ci environment?

**Comment by chilicat** [comment]
No - there is currently no plugin to show the results directly in Jenkens.
You can of course browse to the artifacts to open the generated html pages.

**Comment by chrkaatz** [comment]
allright, thank you.

**Comment by pcgayan** [comment]
I had the same issue, I used HTML report plugin in Jenkins

**Comment by chrkaatz** [comment]
after all i used the html report plugin as well.
